### PR TITLE
Flask setup

### PR DESCRIPTION
**Pull request by ErikSearle**
Setup the directory structure, initialized the flask app, and wrote
a basic readme. Database will still need to be initialized.

-Erik Searle

### CODE REVIEW

**Review by MichaelKowal — APPROVED** [review]
No issues.  This is a good start

**Comment by GraemeRMorgan** [comment]
Looks great.

**Review by GraemeRMorgan — APPROVED** [review]
Will we have to individually .gitignore our own venv folders?

**Comment by ErikSearle** [comment]
I believe git is smart enough to ignore venvs automatically unless you specifically ask it to track them, but it doesn't hurt to just add it to the .gitignore anyway.

**Pull request merged**
